import type { Metadata } from "next";
import {   Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";



const poppins = Inter({
 weight:['100','200','300','400','500','600','700','800'],
 subsets:['latin']
  
 });

export const metadata: Metadata = {
  title: "Panaverse Dao clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className} >
      <Header />
        {children} 
        <Footer />
        
      
        </body>
    </html>
  );
}
